name: Auto Report

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure OpenVPN
        env:
          users: ${{ secrets.USERS }}
        run: |
          sudo apt update
          sudo apt-get --assume-yes --no-install-recommends install openvpn
          python3 ovpn.py
          touch vpn.log

      - name: Connect and Test OpenVPN Connection
        if: always()
        run: sudo ./ovpn.sh

      - name: Report
        if: always()
        env:
          users: ${{ secrets.USERS }}
        run: "python -u main.py"

      - name: Kill OpenVPN Connection
        if: always()
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn

      - name: Upload VPN logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: VPN logs
          path: vpn.log