name: Auto Report

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pull Remote
        env:
          PULL_REMOTE: ${{ secrets.PULL_REMOTE }}
        if: env.PULL_REMOTE != ''
        run: |
          wget -O remote.zip https://github.com/BlueFisher/SHU-selfreport/archive/refs/heads/master.zip
          unzip remote.zip

      - name: Report Without OpenVPN
        if: always()
        env:
          USERS: ${{ secrets.USERS }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
          PULL_REMOTE: ${{ secrets.PULL_REMOTE }}
        run: |
          if [[ $PULL_REMOTE != '' ]]; then
            echo "Report from remote";
            python -u SHU-selfreport-master/main.py;
            if [ $? -ne 0 ] ; then
              echo "USE_OVPN=1" >> $GITHUB_ENV;
            fi
          else
            echo "Report from local";
            python -u main.py;
            if [ $? -ne 0 ] ; then
              echo "USE_OVPN=1" >> $GITHUB_ENV;
            else
              echo $?;
            fi
          fi

      - name: Configure OpenVPN
        env:
          USERS: ${{ secrets.USERS }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
        if: env.HTTPS_PROXY == '' && env.USE_OVPN != ''
        run: |
          sudo apt update
          sudo apt-get --assume-yes --no-install-recommends install openvpn
          python3 ovpn.py
          touch vpn.log

      - name: Connect and Test OpenVPN Connection
        env:
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
        if: env.HTTPS_PROXY == '' && env.USE_OVPN != ''
        run: sudo ./ovpn.sh

      - name: Report
        if: env.HTTPS_PROXY == '' && env.USE_OVPN != ''
        env:
          USERS: ${{ secrets.USERS }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
          PULL_REMOTE: ${{ secrets.PULL_REMOTE }}
        run: |
          if [[ $PULL_REMOTE != '' ]]; then
            echo "Report from remote";
            python -u SHU-selfreport-master/main.py;
          else
            echo "Report from local";
            python -u main.py;
          fi

      - name: Kill OpenVPN Connection
        env:
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
        if: env.HTTPS_PROXY == '' && env.USE_OVPN != ''
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn

      - name: Upload VPN logs
        uses: actions/upload-artifact@v2
        env:
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
        if: env.HTTPS_PROXY == '' && env.USE_OVPN != ''
        with:
          name: VPN logs
          path: vpn.log
